#!/usr/bin/env node
import { readdirSync, existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = fileURLToPath(new URL('.', import.meta.url));
const repoRoot = resolve(__dirname, '..', '..', '..');
const toolsDir = join(repoRoot, 'tools');
const outFile = join(repoRoot, 'hub', 'core', 'src', 'tool-registry.generated.ts');

function loadToolMeta(pkgPath) {
  const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'));
  const meta = pkg.tooldepot;
  if (!meta || !meta.id) return null;
  const toolDir = resolve(pkgPath, '..');
  const name = toolDir.split(/[/\\]/).pop();
  const toolRel = 'tools/' + name;
  const entry = {};
  for (const key of ['core', 'cli', 'desktop']) {
    const rel = meta.entry && meta.entry[key];
    // Store paths relative to the repo root (e.g. "tools/calc/dist/cli/index.js")
    // so the generated registry is portable across machines/OSes. Consumers
    // resolve these against a known root at runtime.
    entry[key] = rel
      ? `${toolRel}/${rel.replace(/\\/g, '/').replace(/^\.\//, '')}`
      : rel;
  }
  return {
    id: meta.id,
    name: typeof meta.name === 'string' ? meta.name : meta.id,
    description: typeof meta.description === 'string' ? meta.description : '',
    category: typeof meta.category === 'string' ? meta.category : 'utility',
    entry,
    bin: typeof meta.bin === 'string' ? meta.bin : undefined,
  };
}

const tools = [];
if (existsSync(toolsDir)) {
  for (const name of readdirSync(toolsDir)) {
    if (name === '_template') continue;
    const pkgPath = join(toolsDir, name, 'package.json');
    if (!existsSync(pkgPath)) continue;
    try {
      const meta = loadToolMeta(pkgPath);
      if (meta) tools.push(meta);
    } catch (e) {
      console.warn(`[sync-tools] skip ${name}: ${e.message}`);
    }
  }
}

// Serialize tool metadata as a TS object literal so the generated file passes
// biome's formatter (single-quoted strings, unquoted identifier keys) without a
// reformat pass. Mirrors JSON.stringify semantics: undefined-valued keys are
// omitted, and keys that are not valid identifiers keep their single quotes.
function isIdentKey(k) {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(k);
}

function quoteKey(k) {
  return isIdentKey(k) ? k : "'" + k.replace(/\\/g, '\\\\').replace(/'/g, "\\'") + "'";
}

function quoteStr(s) {
  return "'" + s.replace(/\\/g, '\\\\').replace(/'/g, "\\'") + "'";
}

function toTsLiteral(value, depth) {
  const pad = '  '.repeat(depth);
  const padInner = '  '.repeat(depth + 1);
  if (Array.isArray(value)) {
    if (value.length === 0) return '[]';
    const items = value.map((v) => padInner + toTsLiteral(v, depth + 1) + ',');
    return '[\n' + items.join('\n') + '\n' + pad + ']';
  }
  if (value !== null && typeof value === 'object') {
    const keys = Object.keys(value).filter((k) => value[k] !== undefined);
    if (keys.length === 0) return '{}';
    const items = keys.map(
      (k) => padInner + quoteKey(k) + ': ' + toTsLiteral(value[k], depth + 1) + ','
    );
    return '{\n' + items.join('\n') + '\n' + pad + '}';
  }
  if (typeof value === 'string') return quoteStr(value);
  return String(value);
}

const ts =
  '// AUTO-GENERATED by hub/core/scripts/sync-tools.mjs. Do not edit by hand.\n' +
  "import type { ToolDepotMeta } from '@tooldepot/types';\n\n" +
  'export const toolRegistry: ToolDepotMeta[] = ' +
  toTsLiteral(tools, 0) +
  ';\n';

writeFileSync(outFile, ts, 'utf8');
console.log(`[sync-tools] wrote ${tools.length} tool(s) to ${outFile}`);
