#!/usr/bin/env node
import { readdirSync, existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = fileURLToPath(new URL('.', import.meta.url));
const repoRoot = resolve(__dirname, '..', '..', '..');
const toolsDir = join(repoRoot, 'tools');
const outFile = join(repoRoot, 'hub', 'core', 'src', 'tool-registry.generated.ts');

function loadToolMeta(pkgPath) {
  const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'));
  const meta = pkg.tooldepot;
  if (!meta || !meta.id) return null;
  const toolDir = resolve(pkgPath, '..');
  const name = toolDir.split(/[/\\]/).pop();
  const toolRel = 'tools/' + name;
  const entry = {};
  for (const key of ['core', 'cli', 'desktop']) {
    const rel = meta.entry && meta.entry[key];
    // Store paths relative to the repo root (e.g. "tools/calc/dist/cli/index.js")
    // so the generated registry is portable across machines/OSes. Consumers
    // resolve these against a known root at runtime.
    entry[key] = rel
      ? `${toolRel}/${rel.replace(/\\/g, '/').replace(/^\.\//, '')}`
      : rel;
  }
  return {
    id: meta.id,
    name: typeof meta.name === 'string' ? meta.name : meta.id,
    description: typeof meta.description === 'string' ? meta.description : '',
    category: typeof meta.category === 'string' ? meta.category : 'utility',
    entry,
    bin: typeof meta.bin === 'string' ? meta.bin : undefined,
  };
}

const tools = [];
if (existsSync(toolsDir)) {
  for (const name of readdirSync(toolsDir)) {
    if (name === '_template') continue;
    const pkgPath = join(toolsDir, name, 'package.json');
    if (!existsSync(pkgPath)) continue;
    try {
      const meta = loadToolMeta(pkgPath);
      if (meta) tools.push(meta);
    } catch (e) {
      console.warn(`[sync-tools] skip ${name}: ${e.message}`);
    }
  }
}

const ts =
  '// AUTO-GENERATED by hub/core/scripts/sync-tools.mjs. Do not edit by hand.\n' +
  "import type { ToolDepotMeta } from '@tooldepot/types';\n\n" +
  'export const toolRegistry: ToolDepotMeta[] = ' +
  JSON.stringify(tools, null, 2) +
  ';\n';

writeFileSync(outFile, ts, 'utf8');
console.log(`[sync-tools] wrote ${tools.length} tool(s) to ${outFile}`);
